name: CI
on:
  - push
  - pull_request

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        ruby:
          - 3.1.2
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundle-cache: true
      - run: bundle exec rake spec